version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      HOST: ${HOST}
      DATABASE: ${DATABASE}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DATABASE_URL: ${DATABASE_URL}
      PORT: 8000
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres-data:


